FROM adoptopenjdk/openjdk14:alpine-slim
COPY target/studentdetails-0.0.1-SNAPSHOT.jar studentdetails-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-jar", "studentdetails-0.0.1-SNAPSHOT.jar"]
 